backend:
  name: github
  repo: etalab/transport-site
  open_authoring: false

publish_mode: editorial_workflow

media_folder: "blog/static/images" # Folder where user uploaded files should go
public_folder: "blog/images"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "blog/content/billets" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Tags",
          name: "tags",
          widget: select,
          multiple: true,
          create: true,
          options:
            [
              "réutilisation",
              "qualité des données",
              "retour d'expérience",
              "tutoriel",
            ],
        }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
